version: '3'
services:
  spark-master:
    build: ./dockerfile/master
    restart: always
    container_name: spark-master
    ports:
      - "8080:8080"
      - "7077:7077"
      - "4040:4040"
    volumes:
      - ./app:/app
  spark-worker-1:
    build: ./dockerfile/worker
    restart: always
    container_name: spark-worker-1
    depends_on:
      - spark-master
    ports:
      - "8081:8081"
    volumes:
      - ./app:/app
  spark-worker-2:
    build: ./dockerfile/worker
    restart: always
    container_name: spark-worker-2
    depends_on:
      - spark-master
    ports:
      - "8082:8081"
    volumes:
      - ./app:/app
  spark-worker-3:
    build: ./dockerfile/worker
    restart: always
    container_name: spark-worker-3
    depends_on:
      - spark-master
    ports:
      - "8083:8081"
    volumes:
      - ./app:/app

  pyspark-notebook:
    image: jupyter/pyspark-notebook:spark-3.3.0
    restart: always
    container_name: pyspark-notebook
    depends_on:
      - spark-master
    ports:
      - "8888:8888"
    environment:
      - "JUPYTER_TOKEN=zbeub"
    volumes:
      - ./app:/home/jovyan